
pipeline{

agent any
stages{
    stage("Git Checkout"){
      steps{
        git credentialsId: 'Github-Devops', url: 'https://github.com/linga-devops/Hello-My-App.git'
            }
          }

stage("Maven Build"){
steps{
 sh "mvn clean package"
 sh "mv target/*.war target/myweb.war"
 }
}

stage("deploy-dev")
{
steps{
  sshagent(['tomcat-new']){
   sh """
    scp -o StrictHostKeyChecking=no target/myweb.war ec2-user@172.31.19.241:/opt/tomcat/apache-tomcat-9.0.82/webapps/
    ssh ec2-user@172.31.19.241 /opt/tomcat/apache-tomcat-9.0.82/bin/shutdown.sh
    ssh ec2-user@172.31.19.241 /opt/tomcat/apache-tomcat-9.0.82/bin/startup.sh
     """ 
            }
    }
  }

}
}
